-- Configs
require("configs.impatient")
require("configs.material")
require("configs.nvim-tree")
require("configs.lualine")
require("configs.bufferline")
require("configs.autopairs")
require("configs.whichkey")
require("configs.tree-sitter")
require("configs.telescope")
require("configs.project")
require("configs.lsp-installer")
require("configs.alpha")
require("configs.indent")
require("configs.cmp")
require("configs.lsp-config")
require("configs.toggleterm")
require("configs.gitsigns")
require("configs.comments")
require("configs.autosave")
require("configs.trouble")
require("configs.lspsaga")
require("configs.outline")

-- Core
require("core.defaults")
require("core.plugins")
require("core.keymaps")
require("core.diagnostics")
